In [1]:
import numpy as np

In [6]:
%timeit np.random.binomial(1, 0.5, 30)

5.17 µs ± 187 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
%timeit -n100000 -r10 np.random.binomial(1, 0.5, 30)

5.21 µs ± 168 ns per loop (mean ± std. dev. of 10 runs, 100000 loops each)


In [13]:
%timeit -n 100000 -r 10 for i in range(30): np.random.binomial(1, 0.5)

91.6 µs ± 2.85 µs per loop (mean ± std. dev. of 10 runs, 100000 loops each)


In [7]:
%timeit for i in range(30): np.random.binomial(1, 0.5)

89.6 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
np.random.binomial(1, 0.5, 30)

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0])

In [19]:
def random_reality(m):
    a = np.random.randint(0, 2, m)
    a[a == 0] = -1
    return a

In [20]:
probs = np.random.binomial(1, 0.1, 20)
reality = random_reality(20)
print(probs)
print(reality)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[-1  1  1  1 -1  1  1 -1  1 -1 -1  1  1 -1 -1  1  1 -1  1 -1]


In [21]:
[(-1)*r if p == 1 else r for (r, p) in zip(reality, probs)]

[-1, 1, 1, 1, -1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1]

In [41]:
probs = [0.0, 0.5, 1.0, 0.5, 0.0, 1.0]
np.random.binomial(1, probs, 6)

array([0, 0, 1, 1, 0, 1])